### ISSUE TITLE
com.supercell.brawlstars

### ISSUE THREAD

**Issue by 89z** [89z/googleplay#83]
https://play.google.com/store/apps/details?id=com.supercell.brawlstars

`github.com/danieliu/play-scraper/issues/90`

**Comment by 89z** [comment]
Fixed:

~~~
> googleplay -a com.supercell.brawlstars -p 1
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.supercell.brawlstars
Title: Brawl Stars
Creator: Supercell
UploadDate: May 11, 2022
VersionString: 43.248
VersionCode: 43248
NumDownloads: 290.545 M
Size: 366.780 MB
File: APK APK APK APK APK APK
Offer: 0 USD
~~~

**Comment by 89z** [comment]
https://github.com/danieliu/play-scraper/issues/90

**Comment by 89z** [comment]
@vineet-agrawal

**Comment by vineet-agrawal** [comment]
Hi @89z ,

This issue persist, please follow the steps mentioned below to reproduce the issue- 
1. Install latest version of play scraper
- `pip install play_scraper`
2. Import play scraper module in the terminal
- `import play_scraper`
3. fetch the app_info
- `app_info = play_scraper.details('com.supercell.clashofclans')`

**Output:**
![image](https://user-images.githubusercontent.com/106417653/170808630-54d7d8b1-ff0f-4463-9d0d-24f8d876c3fd.png)

**Comment by 89z** [comment]
this is a different package, I cannot help you with Python package

**Comment by vineet-agrawal** [comment]
@89z , to whom should I assign this bug so that, this can be resolved as soon as possible?

**Comment by 89z** [comment]
My package can get the details now.

If you need to use the other package, I cannot help you.
